# Generated by Django 4.1 on 2022-10-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyager_archive', '0003_invoiceadjustmentview_invoiceheaderview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRecordView',
            fields=[
                ('auth_id', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('auth_record', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_record_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BibRecordView',
            fields=[
                ('bib_id', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('bib_record', models.TextField(blank=True, null=True)),
                ('suppressed', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'bib_record_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MfhdRecordView',
            fields=[
                ('mfhd_id', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('mfhd_record', models.TextField(blank=True, null=True)),
                ('suppressed', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'mfhd_record_view',
                'managed': False,
            },
        ),
    ]
