# Generated by Django 4.1 on 2022-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyager_archive', '0004_authrecordview_bibrecordview_mfhdrecordview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibTitle',
            fields=[
                ('bib_id', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bib_title',
                'managed': False,
            },
        ),
    ]
