# Generated by Django 4.1 on 2022-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyager_archive', '0005_bibtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfhdSummaryView',
            fields=[
                ('mfhd_id', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('bib_id', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ('location_code', models.CharField(blank=True, max_length=10, null=True)),
                ('location_name', models.CharField(blank=True, max_length=25, null=True)),
                ('call_number', models.CharField(blank=True, max_length=300, null=True)),
                ('suppressed', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'mfhd_summary_view',
                'managed': False,
            },
        ),
    ]
