{{ if .Values.django.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "voyager-archive.fullname" . }}-externalsecret
  namespace: voyager-archive{{ .Values.django.env.run_env }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: systems-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ include "voyager-archive.fullname" . }}-secrets
  data:
    - secretKey: "DJANGO_SECRET_KEY"
      remoteRef:
        key: {{ .Values.django.externalSecrets.env.django_secret_key }}
    - secretKey: "DJANGO_DB_PASSWORD"
      remoteRef:
        key: {{ .Values.django.externalSecrets.env.db_password }}
{{ end }}
