apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "voyagerarchive.fullname" . }}-externalsecrets
  namespace: voyagerarchive{{ .Values.django.env.run_env }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: systems-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ include "voyagerarchive.fullname" . }}-secrets
  data:
  - secretKey: "DJANGO_SECRET_KEY"
    remoteRef:
      key: {{ .Values.django.externalSecrets.env.django_secret_key }}
  - secretKey: "DJANGO_DB_PASSWORD"
    remoteRef:
      key: {{ .Values.django.externalSecrets.env.db_password }}
  - secretKey: "VA_UCLA_DB_PASSWORD"
    remoteRef:
      key: {{ .Values.django.externalSecrets.env.va_ucla_db_password }}
