{{ if not .Values.django.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voyager-archive.fullname" . }}-secrets
  namespace: voyager-archive{{ .Values.django.env.run_env }}
  labels:
{{ include "voyager-archive.fullname" . | indent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  DJANGO_DB_PASSWORD: {{ .Values.django.env.db_password | b64enc | quote }}
  ALMA_API_KEY: {{ .Values.django.env.alma_api_key | b64enc | quote }}
{{ end }}