# Values for ftva voyager-archive.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# voyager-archive-ftva

replicaCount: 1

image:
  repository: uclalibrary/voyager-archive
  # tag: v0.0.1
  tag: latest
  pullPolicy: Always

nameOverride: ""

fullnameOverride: "voyager-archive-ftva"

service:
  type: NodePort
  port: 80
  
ingress:
  enabled: "true"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: sectigo-acme-clusterissuer
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: 'ftva-voy-archive.library.ucla.edu'
      paths:
        - "/"
  tls:
  - secretName: ftva-voyager-archive-tls
    hosts:
      - ftva-voy-archive.library.ucla.edu

django:
  env:
    run_env: "prod"
    debug: "false"
    allowed_hosts:
      - ftva-voy-archive.library.ucla.edu
    csrf_trusted_origins:
      - https://ftva-voy-archive.library.ucla.edu
    db_backend: "django.db.backends.postgresql_psycopg2"
    db_name: "ftva_voy_archive"
    db_user: "voy_archive_access"
    db_host: "p-d-postgres.library.ucla.edu"
    db_port: 5432
    log_level: "INFO"

  externalSecrets:
    enabled: "true"
    env:
      # Application database used by django
      db_password: "/systems/prodsoftwaredev/voyager-archive/db_password"
      django_secret_key: "/systems/prodsoftwaredev/voyager-archive/django_secret_key"

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
